### ISSUE TITLE
EMD files not closed

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1652]
tomviz 1.3.1, windows 10

If you open an EMD (hdf5) file and then delete it from the pipeline I would expect the file to no longer be "held" by tomviz. However, I am unable to rename EMD files until tomviz is completely closed. File --> reset does not close the EMD files either.

The EMD files should be opened, parsed, loaded and then closed always.

MRC files (as a counter example) are not locked after loading into memory.

**Comment by cjh1** [comment]
@ercius I belive this is now fixed in master by 3c41c74c86bb382b8372fe95acfffae5dbe7fb34

**Comment by cryos** [comment]
Yes, I think Chris discovered this. It was an issue on all platforms, but only matters on Windows where files are locked until the file handle is released. Thanks for reporting, it would be great to get confirmation that this is no longer an issue in master for you.

**Comment by ercius** [comment]
I just downloaded the Windows 64 nightly from the main page. The issue of EMD files being locked is still in this version.

However, the nightly zip file exe has the version number 1.3.0-12-g859324c. I am guessing that the nightly windows builds are broken though.

**Comment by cryos** [comment]
Yes, something must have broken in the upload/symlink logic. Thanks for reporting, we will look into this.

**Comment by mathturtle** [comment]
@ercius For now, try this: https://tomviz.org/files/tomviz_nightly_bin/Tomviz-1.3.1-184-g6cd6bc00.msi

@cryos It looks like the upload logic is messing up the 'latest' version somehow.  The files are still getting uploaded...  I'll keep digging.

**Comment by ercius** [comment]
@mathturtle I grabbed the zip file (changed the URL ending) and things are working as expected. Sorry for not checking the issue history for this bug.

I added #1654 to track the nightly build upload logic issue.
