### ISSUE TITLE
Linux binary package broken (Python encodings)

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#1885]
At least on Ubuntu 18.04 where I don't think they have Python 3.7 Tomviz segfaults:
```
./bin/tomviz 
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'
```
On Arch Linux it works fine, but likely picks up some system packages.

**Comment by cryos** [comment]
I can take a look on my laptop, maybe you have ideas Chris. It is odd as I see `lib/python3.7/encodings/__init__.py` and would expect that to work as we prepend `exe_dir + "/../lib/python3.7"` for Linux.

**Comment by cjh1** [comment]
Ok, so it works on my machine. We give us a good clue. I have python 3.7 install. @bnmajor I assume you don't have python 3.7?

**Comment by bnmajor** [comment]
I did not. I just updated to 3.7 and now it works.

**Comment by cjh1** [comment]
@bnmajor Thanks, yep if picking it up from the install 3.7.

**Comment by cryos** [comment]
It isn't super clear, but [this Python bug report](https://bugs.python.org/issue35596) gives some clues on things that might go wrong. I can reproduce by renaming my encodings file and wonder if we are hitting something odd.

**Comment by cjh1** [comment]
So if I add <install path>/python3.7 to my PYTHONPATH, then it also works. So think the prepend [here](https://github.com/OpenChemistry/tomviz/blob/master/tomviz/tomvizPythonConfig.h.in) is using the wrong path.  Recompiling to confirm what is going on.

**Comment by cjh1** [comment]
OK, so I think I understand this now. The problem is that the prepend [here](https://github.com/OpenChemistry/tomviz/blob/master/tomviz/tomvizPythonConfig.h.in) happens after the Python interpreter has been started, so it will not help it find the `encoding` module. What we need todo is ensure that PYTHONPATH is pointing to the root of the Python we ship ( like we do on Mac ). I have pushed #1886 to test this theory.

**Comment by cryos** [comment]
I just tested out Tomviz-1.6.0-138-ga2a5eba.tar.gz versus -132 and it now works (and 132 still fails). It looks like this is resolved as far as I can tell now - thanks Chris!
