### ISSUE TITLE
Negative numbers in tilt series data sets introduces issues during alignment

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#494]
MRC data from FEI microscopes uses a non-standard MRC format and unsigned integers. tomviz imports this data as shorts (signed integers) which does not lose any data (even though this is unphysical) but creates problems later during tilt series alignment. For example, when doing shift alignments, areas shifted from outside of the data are set to 0. This is not the minimum value of a data set with negative values. This causes the reconstruction algorithm to introduce a "block" of density around the edges of the data.
![image](https://cloud.githubusercontent.com/assets/15657108/16824037/4876019c-491d-11e6-9d2e-b6923a4481e4.png)
- Notice large number of 0 values in histogram, and "gray" values at the bottom of the shifted image.

Here are some suggestions for resolving this automatically:
1) Import data as unsigned integers (aka unsigned shorts) to match how the data was written (0 - 65535). I am not sure if tomviz allows for unsigned integers though.

2) import the data as signed integers, cast to float, set minimum to zero

3) Use the array's minimum value as the "cval" option in ndimage.interpolation.shift()

**Comment by mathturtle** [comment]
> uses a non-standard MRC format

Ok, we already have a problem here.  I'm not sure how much we can do to help this in an automated way.  I don't know if changing the reader to handle this will break the reader for some other data file.  If you have any more details on what their non-standard format is, can you link to them on here?  Is there a way to tell if a file is in this format versus a normal MRC file?

> 1) Import data as unsigned integers (aka unsigned shorts) to match how the data was written (0 - 65535). I am not sure if tomviz allows for unsigned integers though.

Like I mentioned above changing the reader to support this will be tricky.

> 2) import the data as signed integers, cast to float, set minimum to zero

Are the negative values bad data?  I think you will be losing valuable data here.  For signed/unsigned short the negative values are the ones that were originally greater than 32768.

> 3) Use the array's minimum value as the "cval" option in ndimage.interpolation.shift()

Hmmm. This might work.  You would need to shift everything less than 0 by +65536 while leaving the zeroes and positive values alone.  You would probably need to convert the data type first too so the values would fit within the range of the new numpy type.  I'm not particularly familiar with scipy, but according to the documentation it might work.  Can you try it?  It would be fairly simple to add a python operator in the data transforms menu to fix this.

**Comment by ercius** [comment]
Here is [a link](http://bio3d.colorado.edu/imod/doc/mrc_format.txt) to an explanation of the MRC standard. Notice that the mode determines the data type and that mode == 6 is unsigned integer (non standard). Im not sure how the tomviz reader handles mode == 6, but this might be an easy way to fix this.

The FEI MRC files are fairly easy to distinguish if you want to be sure about this. You can see an example of the reader in mrc.py (mrc.mrcReader()) that I use at [my repository](https://bitbucket.org/ercius/openncem/src/097463534a9ed438566512da97516d7ecace5a88/mrc.py?fileviewer=file-view-default). See line 70 - 104.

I want to stress that the extra FEI header contains the correct pixel size. The volumeSize value referred to in the standard header is always set to the number of pixels and thus the pixel size will be shown as 1 in tomviz. So, I think tomviz really needs to read this extra information anyway.

> Are the negative values bad data?

No. The negative values are the correct data. As far as I know, if you read data written to uint (0 - 65535) as signed integers then the values just range from (-32535 - 32534) with a constant offset. We cannot simply remove the negative values. Casting to int --> float and then subtracting the min value will just reset that offset and all data will be positive. The actual values do not matter here since the output of the detector is in "counts" which have no real physical meaning quantitatively.

> It would be fairly simple to add a python operator in the data transforms menu to fix this.

This is a viable option but most users would be unfamiliar with this issue. Maybe we could check for negative values upon import and then ask the user to shift them all positively? Negative values may be valid for other data sets such as low dose TEM images.

> Can you try it?

Sure. Ill make a transform to shift all of the values and let you know how that works.

We should think about addressing this case for general users in the long term. The best is to implement mode == 6 as uint in the reader if that is possible.

**Comment by ercius** [comment]
I checked this and casting to float is the only way that tomviz will allow this to work. It seems that the python embedded in tomviz only accepts int or float.

Many more numpy datatypes should be available [as per this help file.](http://docs.scipy.org/doc/numpy/user/basics.types.html). However, I receive an error message for any other datatype:
`NameError: global name 'int16' is not defined`

Here is the code to cast to float and shift all the values positive:
```
def transform_scalars(dataset):
    """Define this method for Python operators that 
    transform the input array"""

    from tomviz import utils
    import numpy as np

    # Get the current volume as a numpy array.
    array = utils.get_array(dataset)
    #array = array.astype(float)
    # This is where you operate on your data, here we square root it.
    result = array.astype(float) - np.amin(array).astype(float)

    # This is where the transformed data is set, it will display in tomviz.
    utils.set_array(dataset, result)
```

**Comment by mathturtle** [comment]
I think for those other datasets you have to do `np.int16`.  If you just put `int16` it searches the global python namespace where it is not defined.  The only datatypes that python understands in that global namespace are int and float.

**Comment by mathturtle** [comment]
That is the MRC standard I was working from... Digging into the vtkMRCReader, it was supposed to already handle this case, but since I didn't have test files for all of the types of MRC files this bug must have slipped through.  Can you send me an example file to test with please?

**Comment by ercius** [comment]
@mathturtle Your first comment is correct. astype also accepts np.uint16 and other dtypes. So the code below works but is specific to int16 --> uint16 conversions. This could be generalized but would have to take numerous cases into account. The old version uses floats and is more general (although memory intensive).
```
def transform_scalars(dataset):
    """Define this method for Python operators that 
    transform the input array"""

    from tomviz import utils
    import numpy as np

    # Get the current volume as a numpy array.
    array = utils.get_array(dataset).astype(np.float32)
    #array = array.astype(float)
    # This is where you operate on your data, here we square root it.
    result = array - np.amin(array)

    # This is where the transformed data is set, it will display in tomviz.
    utils.set_array(dataset, result.astype(np.uint16))
```

As for you second comment I can provide MRC files. What is your preference for receiving >200 MB files?

**Comment by mathturtle** [comment]
> The old version uses floats and is more general

Sort of.  You would need to change your negative value fixing line to: `array[array < 0] += 65536` because that is the conversion from int16 to uint16.  And the more specific version may warn/fail since it is an unsafe (data changing) operation.  Apparently numpy has a flag you have to set to enable those.  But you can't do this generally.  You have to know the data type you are converting from and what it should be.

> What is your preference for receiving >200 MB files?

I don't really have one.  I've never had this problem before.  You can use anything you want (send links/share to my Kitware email address which should be visible on Github.  If you use Google Drive, it is a gmail account so you can share to it directly).

**Comment by ercius** [comment]
>  You would need to change your negative value fixing line to: array[array < 0] += 65536

I do not think this will work for tomography data. This will fit all negative integer values into the values above 32768. I want to keep the values in the same order, but just shift all the values to positive values.  The actual minimum does not matter just the order of intensities. I can provide some more context in the near future,

> If you use Google Drive, it is a gmail account so you can share to it directly

I sent you a file through google drive and can provide more if necessary.

**Comment by mathturtle** [comment]
> The actual minimum does not matter just the order of intensities.

That's what I'm trying to fix.  If it is reading in unsigned integers as signed integers, then the values greater than 32767 will get interpreted as negative values according to the inverse of that transform.  So your order is already messed up and that transform should fix it.

> I sent you a file through google drive and can provide more if necessary.

I got it, thanks!  I'll take a look at what is happening tomorrow.

**Comment by ercius** [comment]
> That's what I'm trying to fix. If it is reading in unsigned integers as signed integers, then the values greater than 32767 will get interpreted as negative values according to the inverse of that transform. So your order is already messed up and that transform should fix it.

Ah! Now I see the miscommunication here. Your assumption that the order is incorrect...is incorrect. The image I see using the orthoslice for the integer data (see screenshot in first post of two crossing wires surrounded by vacuum) **looks** exactly like the image I acquired on the microscope as uint data. However, the data values range from -32000 to 32000 instead of 0 to 65000. The MRC uint16 data was read as signed 16 bit integers, but are still in the correct "order".  In this case, reading uint16 as int16 does not have the wrap around effect you are referencing.

Sorry for the misunderstanding. I used my transform to shift the values in this data set and ended up with an excellent reconstruction of this data. So, I know it works in this case.

**Comment by mathturtle** [comment]
Ok, I misunderstood.  And looking at the file, I see why it is reading in the data that way.  In the file you sent me mode is 1, not 6.  A mode of 1 being interpreted as signed 16 bit integers is correct.

So what you would like is a transform to convert the data to floating point and add a constant to it so that the minimum is 0?

**Comment by ercius** [comment]
Im sorry. There might be other MRC files I have that have mode = 6. I guess FEI changed it, but its weird to write uint16 --> int16 and then have people work with negative numbers. FEI makes weird decisions in their programs. Anyway...

> So what you would like is a transform to convert the data to floating point and add a constant to it so that the minimum is 0?

I guess it would be best to cast to float, shift the values to positive by 32768 ((2^16)/2), and then cast to uint16. That would produce the same values (+/- 1?) as were measured by the microscope.

**Comment by ercius** [comment]
bump @mathturtle 

I still have issues with this when reading some MRC files from FEI instruments that indicate the uint16 data is int16. I use a custom transform to cast to float and subtract the array minimum (or shift by 0.5*2^16). It would be useful to add such a transform to the list.

**Comment by cjh1** [comment]
@mathturtle Do we have a way forward for this issue?

**Comment by mathturtle** [comment]
@cjh1 I'm not sure.  @ercius hasn't sent me a file that demonstrates this.  We could add the transform he suggests, but I'm not sure what else could be done for this.  MRC is somewhat loosely defined as a format and if FEI is generating files inconsistent with the majority of the format definitions I have seen then I'm not sure how we can handle that since it will break another MRC file writer's files.

**Comment by cryos** [comment]
What about adding a simple transform that applies this using numpy, set defaults to what was suggested and offer simple UI/ability to edit code to do more. This would be a useful example filter too for manipulating voxel values using basic math.

**Comment by cquammen** [comment]
I can whip up a transform if no one else is working on it.

**Comment by cquammen** [comment]
Here's a transform that strictly does the task needed in this issue, which is reinterpreting integral types to unsigned integral types:

```
def transform_scalars(dataset):
    """Reinterpret a signed integral array type to its unsigned counterpart.
    This can be useful when a data array is read in as a signed array when
    it should have been read in as an unsigned array."""

    from tomviz import utils
    import numpy as np
    scalars = utils.get_scalars(dataset)
    if scalars is None:
        raise RuntimeError("No scalars found!")

    dtype = scalars.dtype
    dtype = dtype.type

    typeMap = {
        np.int8 : np.uint8,
        np.int16 : np.uint16,
        np.int32 : np.uint32
    }

    typeAddend = {
        np.int8 : 128,
        np.int16 : 32768,
        np.int32 : 2147483648
    }

    if dtype not in typeMap:
        raise RuntimeError("Scalars are not int8, int16, or int32")

    newType = typeMap[dtype]
    addend = typeAddend[dtype]

    newScalars = scalars.astype(dtype=newType) + addend
    utils.set_scalars(dataset, newScalars)
```

Please advise if you had something else in mind, @cryos .

**Comment by cryos** [comment]
Seems reasonable to me, if it satisfies @ercius use case then let's get it added @cquammen - I hadn't thought too deeply about how it should be done.

**Comment by ercius** [comment]
I just saw this after leaving work. I'll take a look tomorrow and can also
provide an example dataset.

**Comment by cquammen** [comment]
Another possibility - and maybe more generally useful one - add a transform that simply adds a constant to the data. We could include a checkbox to set the constant to the minimum value in the dataset.

**Comment by cryos** [comment]
What you proposed seems like a nice approach, why don't we test that, and we can always add something else later. I would imagine this would be useful where you know there is a type issue, but general mathematical transforms such as adding and/or multiplying the voxel values would be of use too.

**Comment by ercius** [comment]
The transform above transform_scalars(dataset) works just as expected. Ill test it in the binary when it gets incorporated.

I also like the second approach (add a constant with option min() checkbox), which would be more versatile.
