### ISSUE TITLE
The "eye" icon in pipeline doesn't change when modules are highlighted

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#724]
When a visualization module in the pipeline is highlighted, the "eye" icon on the right looks the same when I turn on/off the visualization.
<img width="278" alt="screen shot 2016-11-01 at 11 37 00 pm" src="https://cloud.githubusercontent.com/assets/13088588/19915984/682db37e-a08c-11e6-8a8c-1ae3cf3a4fc0.png">

This is kind of annoying especially when there are multiple datasets and visualization modes.

**Comment by cryos** [comment]
It is grayed, but there is less contrast with the blue background. We can take a look at ways that it might be improved, but even in the screenshot I can see what you mean but see the center is lighter by a few tones. I think we want to keep the transparent background.

**Comment by yijiang1** [comment]
If I only see the screenshot above, I can't tell if the data is visible or not on my computer.
How about using a different icon? Something like this?
![a](https://cloud.githubusercontent.com/assets/13088588/19939420/46554000-a0ff-11e6-801c-07ed7c90025f.png)

**Comment by cquammen** [comment]
How about a closed eye to represent not visible, i.e., no pupil shown?

**Comment by yijiang1** [comment]
I'm ok with any kind of design as long as it's discernible enough.

**Comment by cryos** [comment]
I can see it on my screen, but screens certainly vary. Another option is to look at only selecting the Item rather than the complete row. A closed eye would probably be reasonable, the interaction of the selection color and the background of the selected row certainly makes this harder to see and on poor screens quite possibly impossible.

**Comment by cquammen** [comment]
How about this for not visible?

![image](https://cloud.githubusercontent.com/assets/360056/19979220/0e4421be-a1d0-11e6-9e22-d3b50987cb05.png)

With one visible:

![image](https://cloud.githubusercontent.com/assets/360056/19979254/2fc31084-a1d0-11e6-9d6a-2b5343a31e5e.png)

**Comment by cryos** [comment]
Looks good to me, should be visibly different on even the most washed out of screens.

**Comment by Hovden** [comment]
I like it.

**Comment by cquammen** [comment]
Addressed by #737.

**Comment by cryos** [comment]
Looks great

**Comment by yijiang1** [comment]
There is a bug in #737 : The icon does not update automatically when I click it in the pipeline.

**Comment by cquammen** [comment]
You may have to explicitly run `cmake .` in your build directory for the Qt resource stuff to be set up appropriately. Then build after you do so. Does that fix it?

**Comment by yijiang1** [comment]
I run `sudo cmake .` in my tomviz build directory but the problem is not fixed.

**Comment by cquammen** [comment]
Did you build afterwards?

Clicking on the eye icon toggles it on my local system.

BTW, `cmake` shouldn't normally require use of `sudo`.

**Comment by yijiang1** [comment]
> Did you build afterwards?

I did. I run `cmake --build .` after `cmake .`

**Comment by cquammen** [comment]
Can you post a screen shot of what you are seeing? Thanks for trying this out, by the way.

**Comment by yijiang1** [comment]
<img width="709" alt="screen shot 2016-11-03 at 3 45 51 pm" src="https://cloud.githubusercontent.com/assets/13088588/19982518/bcc47c78-a1dc-11e6-930f-88b81a2d7fb7.png">

<img width="413" alt="screen shot 2016-11-03 at 3 46 25 pm" src="https://cloud.githubusercontent.com/assets/13088588/19982521/be16b028-a1dc-11e6-857d-3e7bf18509ec.png">

**Comment by cquammen** [comment]
How about in the UI? Is it always the open eye icon?

**Comment by yijiang1** [comment]
Yes if I only click the icon and do nothing else.

For example, when I click the eye icon for "Orthogonal Slice", the icon does not change no matter how long I wait.
<img width="273" alt="screen shot 2016-11-03 at 3 58 39 pm" src="https://cloud.githubusercontent.com/assets/13088588/19982932/6a7b7118-a1de-11e6-9878-479e679cd3a7.png">

On the other hand, an update can be triggered by extra actions such as
right-click the module:
<img width="279" alt="screen shot 2016-11-03 at 4 02 58 pm" src="https://cloud.githubusercontent.com/assets/13088588/19983231/93aa71fa-a1df-11e6-8dfb-314687d9d2bd.png">

or click a different module:
<img width="281" alt="screen shot 2016-11-03 at 4 03 13 pm" src="https://cloud.githubusercontent.com/assets/13088588/19983249/9f71ec48-a1df-11e6-804f-67f591469d46.png">

**Comment by cquammen** [comment]
Hmm, how odd. It takes about a second after I click for the eye icon to update, but it does update.

I can't imagine why a change in the image icon would trigger this behavior. Perhaps before the icon change you were seeing the same behavior and that's why the icon didn't look different?

**Comment by yijiang1** [comment]
> Perhaps before the icon change you were seeing the same behavior and that's why the icon didn't look different?

Yeah I think this is the real reason.

BTW, this only happens on my local build. My binary version does update the icon.

**Comment by cryos** [comment]
I see this issue on Linux, the eye icon doesn't update for me until I move out of that row, which triggers a repaint. I think we are missing a signal to say that the row/column has changed, and thus needs a repaint.

**Comment by yijiang1** [comment]
I don't have this problem any more on Mac. 
Feel free to close the issue if it's fixed on other platforms.
