### ISSUE TITLE
Fail to import scipy v0.9.3 Mac OS

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#859]
I get errors when using scipy functions

Traceback (most recent call last):
  File "Gaussian Filter", line 6, in transform_scalars
  File "/Applications/tomviz.app/Contents/Python/scipy/ndimage/__init__.py", line 172, in <module>
    from .filters import *
  File "/Applications/tomviz.app/Contents/Python/scipy/ndimage/filters.py", line 37, in <module>
    from scipy.misc import doccer
  File "/Applications/tomviz.app/Contents/Python/scipy/misc/__init__.py", line 47, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "/Applications/tomviz.app/Contents/Python/scipy/special/__init__.py", line 586, in <module>
    from ._ufuncs import *
ImportError: dlopen(/Applications/tomviz.app/Contents/Python/scipy/special/_ufuncs.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Applications/tomviz.app/Contents/MacOS/../Libraries/libgfortran.3.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/tomviz.app/Contents/MacOS/../Libraries/libgfortran.3.dylib
Failed to execute the script. (:0, )

**Comment by mathturtle** [comment]
@cryos I can reproduce.  And I think the problem is this part (emphasis added):

> Referenced from: /Applications/tomviz.app/Contents/MacOS/../Libraries/libgfortran.3.dylib (**which was built for Mac OS X 10.12**)

@yijiang1 What version of OSX are you using?

**Comment by yijiang1** [comment]
OS X El Capitan 10.11.6

**Comment by cryos** [comment]
I updated the binary, and the nightly, if you give them a try they will hopefully be working better.

**Comment by yijiang1** [comment]
I still get errors on latest binary (0.9.3-2-ge47bb8d).

**Comment by Hovden** [comment]
I moved forward with promoting this release. We have nearly a hundred new users downloading v0.9.3

**Comment by mathturtle** [comment]
> We have nearly a hundred new users downloading v0.9.3

Hopefully most of them run Sierra and downloaded before we found this.  I don't think the newer binary will work there either... I only had half the fix we needed, and the halfway fix won't work anywhere.  Anyway, I think I've fixed the rest now and a new package is building.

**Comment by Hovden** [comment]
I see, if it works on the latest OSX then we should simply make note of that in the installation instructions.

**Comment by cryos** [comment]
I should have an updated installer shortly that will work on older versions, and I think we should support them. It has finished generating, just going to get someone to test it out.

**Comment by cryos** [comment]
Updated the binary for the release at http://www.tomviz.org/downloads/, Shawn just tested it and it looked good. This should support at least down to 10.10, which I think is reasonable. I can update the page to say that is our new minimum (most would work down to 10.9, but SciPy will not).

**Comment by yijiang1** [comment]
I upgraded my system to Sierra (v10.12.3) and the still get errors on 0.9.3-2-ge47bb8d.
The newer version (0.9.3-16-g6b94623) does fix the problem.

**Comment by cryos** [comment]
The binary installer was fixed at http://www.tomviz.org/downloads/ for older versions of macOS, i.e. 0.9.3, and the later builds will work. The 0.9.3-2-ge47bb8d needed some extra changes to the fortran library, and so will never work. It sounds like this is resolved, and in our testing it at least worked on El Capitan, and should go back to 10.10.
